language: php

php:
    - '7.4'

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - cd tests && php test-old.php
    - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no .

